FROM php:8.0-apache

# Install PDO extension
RUN docker-php-ext-install pdo pdo_mysql

# Copy the PHP files
COPY . /var/www/html

# Set Apache document root
RUN sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf
RUN sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

EXPOSE 80

CMD ["apache2-foreground"]
